Repository teamesa/kilometer_backend, pull requests merged in 2023-02, with the labels that each got.

#218 [chore] 이슈 등록을 위한 템플릿과 PR 등록을 위한 템플릿 양식을 등록한다.
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#231 [refactor] ArchiveImage와 UserVisitPlace Entity객체명 마지막에 Entity를 접미사로 추가한다.
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveAggregateConverter.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/archiveImage/ArchiveImageEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/archiveImage/ArchiveImageRepository.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/archiveImage/ArchiveImageService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/PlaceInfo.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/request/ArchiveRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/userVisitPlace/UserVisitPlaceEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/userVisitPlace/UserVisitPlaceRepository.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/userVisitPlace/UserVisitPlaceService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
Labels: refactor

#239 [infra] PR merge를 하면 Jenkins를 통한 자동 CI/CD 환경을 구축한다.
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ItemController.java
Labels: enhancement

#237 [feat] 실시간 아카이브 API 구현
  .gitignore
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/HomeController.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchiveDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchivesResponse.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/HeartDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/IntroductionDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/MetaDataDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/PhotoDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/TitleDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/UserDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/ApiGenerator.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/HomeModuleApiFactory.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/StringConvertor.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchiveDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchivesResponseTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/HeartDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/IntroductionDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/MetaDataDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/PhotoDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/TitleDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/UserDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/util/ApiGeneratorTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/util/HomeModuleApiFactoryTest.java
  kilometer-backend-api/src/test/java/com/kilometer/common/Fixture.java
  kilometer-backend-domain/build.gradle
  kilometer-backend-domain/src/main/generated/com/kilometer/domain/pick/QPick.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveRepositoryCustom.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/MyArchiveDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/RealTimeArchiveDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/realTimeArchive/RealTimeArchiveHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/realTimeArchive/dto/RealTimeArchiveResponse.java
  kilometer-backend-domain/src/test/java/com/kilometer/archive/ArchiveRepositoryTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/common/Fixture.java
  kilometer-backend-domain/src/test/java/com/kilometer/common/annotation/SpringTestWithData.java
  kilometer-backend-domain/src/test/java/com/kilometer/common/support/DataCleaner.java
  kilometer-backend-domain/src/test/java/com/kilometer/common/support/DataClearExtension.java
  kilometer-backend-domain/src/test/java/com/kilometer/homeModules/modules/realTimeArchive/RealTimeArchiveHandlerTest.java
  kilometer-backend-domain/src/test/resources/application.yml
Labels: enhancement

#240 [refactor] 전시글 소개 API의 @Deprecated 제거 및 엔티티 @Where 애노테이션 값 변경
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ItemController.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/archiveImage/ArchiveImageEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/like/Like.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/userVisitPlace/UserVisitPlaceEntity.java
Labels: refactor

#234 [feat] 아이템 조회 api 호출할 때 item summary, item images 포함하도록 수정
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ItemController.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemAggregateConverter.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemInfoResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetail/ItemDetailRepository.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetailImage/ItemDetailImageRepository.java
Labels: enhancement

#242 [fix] 아카이브 수정 버그 픽스
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ArchiveController.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/HelloController.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/security/exception/ErrorStatusMapper.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/exception/ArchiveUnauthorizedException.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/request/ArchiveRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/exception/KilometerErrorCode.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/ArchiveServiceTest.java
Labels: bug

#235 [feat] SPRINT-32 BO 수정
  kilometer-backend-backoffice/src/main/resources/static/js/module.js
  kilometer-backend-backoffice/src/main/resources/templates/home/key_visual/keyVisual.html
  kilometer-backend-backoffice/src/main/resources/templates/home/key_visual/updateKeyVisual.html
  kilometer-backend-backoffice/src/main/resources/templates/home/modules.html
  kilometer-backend-backoffice/src/main/resources/templates/home/updateModules.html
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/KeyVisualValidator.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/ModuleValidator.java
Labels: enhancement

#247 [feat] 미전시 정책 반영
  kilometer-backend-api/src/main/java/com/kilometer/backend/security/exception/ErrorStatusMapper.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/swipeItem/SwipeItemHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/swipeItem/dto/SwipeItemDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemEntityMapper.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepository.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustom.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/domain/Item.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemInfoDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/exception/ItemExposureOffException.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/exception/ItemNotFoundException.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/exception/KilometerErrorCode.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/ArchiveServiceTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/item/ItemServiceTest.java
Labels: enhancement

#254 [feat] 전시글 요약정보 반환 api 샘플링
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ItemController.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemSummaryResponse.java
Labels: enhancement

#246 [feat, refactor] 홈 데이터 응답 시 데이터가 없는 모듈 생략, 이달의 무료 티켓 조회 로직 변경
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ListItemAdditionalInfoDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/MonthlyFreeTicketContentDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/MonthlyFreeTicketsResponse.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/TitleDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/TypeBadgeDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchiveDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchivesResponse.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/MetaDataDto.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/HomeModuleApiFactory.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ListItemAdditionalInfoDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/MonthlyFreeTicketContentDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/MonthlyFreeTicketsResponseTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/TitleDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/TypeBadgeDtoTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchivesResponseTest.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/util/ApiGeneratorTest.java
  kilometer-backend-api/src/test/java/com/kilometer/common/Fixture.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/RealTimeArchiveDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/HomeRenderingService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/ModuleHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/keyVisual/KeyVisualHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemRepository.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/dto/MonthlyFreeTicketResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/realTimeArchive/RealTimeArchiveHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/swipeItem/SwipeItemHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustom.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/MonthlyFreeTicketDto.java
  kilometer-backend-domain/src/test/java/com/kilometer/archive/ArchiveRepositoryTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/common/Fixture.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/item/ItemRepositoryTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/homeModules/modules/realTimeArchive/RealTimeArchiveHandlerTest.java
Labels: enhancement, refactor

#255 [refactor] ArchiveImage와 UserVisitPlace 도메인 객체를 생성한다.
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveAggregateConverter.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/PlaceType.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/domain/Archive.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/domain/ArchiveImage.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/domain/userVisitPlace/PlaceType.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/domain/userVisitPlace/UserVisitPlace.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/PlaceInfo.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/request/ArchiveRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/userVisitPlace/UserVisitPlaceEntity.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/common/statics/Statics.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/ArchiveServiceTest.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/domain/ArchiveImageTest.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/domain/ArchiveTest.java
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/archive/domain/UserVisitPlaceTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/archive/ArchiveRepositoryTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/homeModules/modules/realTimeArchive/RealTimeArchiveHandlerTest.java
Labels: refactor

#257 [FEAT] User Validation & Namg Geneartor 20자 이내로 만들기 수정
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/UserValidationExceptionHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/exception/UserValidationException.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/user/NameGenerator.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/user/User.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/user/UserFormValidator.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/user/dto/UserUpdateRequest.java
Labels: enhancement

#263 [feat] Item 엔티티에 출처 필드를 추가한다.
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemInfoResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetail/ItemDetail.java
  kilometer-backend-domain/src/main/resources/db/migration/V16_add_item_detail_column.sql
  kilometer-backend-domain/src/test/groovy/com/kilometer/domain/item/itemDetail/ItemDetailTest.java
Labels: enhancement

#266 [fix] 실시간 아카이브 좋아요 링크 변경
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/HeartDto.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/realtimearchive/HeartDtoTest.java
Labels: bug

#259 [feat] 전시글 - pick 미전시 대응
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickRepository.java
Labels: enhancement

#262 [feat] 아카이브 수정, 등록시 필요한 전시글 정보 반환 api
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/ItemController.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveAggregateConverter.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/ArchiveDetailResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustom.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemForArchive.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemSummary.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemSummaryResponse.java
Labels: enhancement

#272 [feature] Backoffice 출처 표시
  .github/PULL_REQUEST_TEMPLATE.md
  kilometer-backend-backoffice/src/main/java/com/kilometer/backend/controller/ItemController.java
  kilometer-backend-backoffice/src/main/resources/templates/form/addForm.html
  kilometer-backend-backoffice/src/main/resources/templates/form/updateItemForm.html
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemEntity.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/DetailRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemCreateRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemUpdateRequest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemUpdateResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetail/DetailCommand.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetail/DetailCommandService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/item/itemDetail/ItemDetail.java
Labels: enhancement

#273 [FEAT] My archive item 정보 추가
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveAggregateConverter.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveRepositoryCustomImpl.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/ArchiveService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/MyArchiveDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/archive/dto/MyArchiveInfo.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/util/ApiUrlUtils.java
Labels: enhancement

#276 [refactor] 제네릭 오남용 수정, ModuleHandler 테스트 추가
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/HomeController.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/MonthlyFreeTicketsResponse.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/realtimearchive/ArchivesResponse.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/ApiGenerator.java
  kilometer-backend-api/src/main/java/com/kilometer/backend/util/HomeModuleApiFactory.java
  kilometer-backend-api/src/test/java/com/kilometer/backend/util/HomeModuleApiFactoryTest.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/HomeApiResponse.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/HomeRenderingService.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/ModuleResponseDto.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/ModuleHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/keyVisual/KeyVisualHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/realTimeArchive/RealTimeArchiveHandler.java
  kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/swipeItem/SwipeItemHandler.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/keyVisual/KeyVisualHandlerTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/realTimeArchive/RealTimeArchiveHandlerTest.java
  kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/swipeItem/SwipeItemHandlerTest.java
Labels: refactor
